### PR TITLE
Reviews of input data check and format

### PR DESCRIPTION
**Pull request by RonaldoCMP**
Here is an extensive review of common.scad, vectors.scad, arrays.scad and their regression test codes. The changes were mostly in input data check and format. Some few functions got more changes either to adapt them to the new `asserts `or because a better (faster, simpler) code was found. Some inserted `asserts `have side effects on other file tests:

1. test_math.scad fails trying to do a `vmul` of vectors with different lengths;
2. the same happens with test_shapes.scad and test_shapes2d.scad;

I believe that trying to multiply vectors of different length should be considered an error. I didn't dig into the offending codes yet to see what is wrong.

Another change was moving `add_scalar` from vectors.scad to arrays.scad. It is in fact an array operation. Some few documentation examples and test codes were added. Some function argument names were changed to keep them consistent with the names they have in other similar functions. That name changes were not as extensive as I would like but are advisable to favor users.

Most, but not all, changed function codes are followed by a comment with a short summary of the changes done.  Those comments always start with:
//***

I can eliminate those comments before a merge is done.

### CODE REVIEW

**Comment by RonaldoCMP** [comment]
I did some correction in the code but am unable to submit it again. How I "delete" an unsuccessful PR?

**Comment by revarbat** [comment]
Lemme try deleting it.

**Comment by revarbat** [comment]
I can close it without merging.

**Comment by revarbat** [comment]
You probably need to do a fit pull from the upstream master branch.

**Pull request closed without merging**
